[package]
name = "rknn-rs"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "rknn rust binding"
repository = "https://github.com/frodik13/rknn-rs"

[dependencies]
bytemuck = "1.23.2"
rknn-sys-rs = "0.1.0"

[features]
rknnmrt = ["rknn-sys-rs/rknnmrt"]
